name: Broken Link Check

on:
  schedule:
    # run every Monday at 1pm UTC https://crontab.guru/#0_13_*_*_1
    - cron: 0 13 * * 0 
  workflow_dispatch: # trigger manually
  
jobs:
  check:
    name: Check broken links
    runs-on: ubuntu-latest
    
    steps:
      - name: Broken Link Check MEI
        uses: technote-space/broken-link-checker-action@v2
        with:
          target: https://music-encoding.org/

      - name: Check MEI with ruzickap action
        if: always()
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://music-encoding.org/
      
      
      
  markdown-link-check:
    name: Check markdown links
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/checkout@v2
      with:
        repository: musicEnfanthen/music-encoding.github.io
        ref: master
        path: check-dir
      
    - name: Check file path
      run: |
        ls -alh  
    
    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.8
      id: mlc
      with:
        folder-path: check-dir
        config-file: .github/link-check-config.json
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
   
    - name: Check context
      if: always()
      run: |
        echo "${{ github.repository_owner }}"
        echo "${{ github.repository }}"
        echo "${{ github.context.repo.owner }}"
        echo "${{ github.context.repo.repo }}"
    
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: create-issue
      with:
        filename: .github/broken-link-issue-template.md
    - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
    - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
    
