name: Broken Link Check

on:
  schedule:
    - cron: 0 12 1/7 * * # run weekly
  workflow_dispatch: # run manually
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  check:
    name: Check broken links
    runs-on: ubuntu-latest
    
    steps:
      - name: Broken Link Check MEI
        uses: technote-space/broken-link-checker-action@v2
        with:
          target:  https://music-encoding.org/
          
      - name: Broken Link Check AWG
        uses: technote-space/broken-link-checker-action@v2
        with:
          target:  https://edition.anton-webern.ch/

  markdown-link-check:
    name: Check markdown links
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        repository: musicEnfanthen/music-encoding.github.io
        ref: master
      
    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.8
      with:
        use-verbose-mode: 'yes'
